---
title: "Airbnb dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
set.seed(1)
airbnb_data = read_csv("./data/nyc_airbnb.zip") %>%
  clean_names() %>%
  rename(boro = neighbourhood_group) %>%
  mutate(rating = review_scores_location/2) %>%
  filter(boro == "Manhattan",
         room_type == "Entire home/apt",
         price > 100 & price < 400)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot

```{r}
airbnb_data %>%
  mutate(haver_text = str_c("Price: $", price, '\nRating:', rating)) %>%
  plot_ly(x = ~longitude, y = ~latitude, color = ~price, text = ~haver_text, type = "scatter", mode = "marker", alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot

```{r}
airbnb_data %>%
  mutate(haver_text = str_c("Price: $", price, '\nRating:', rating)) %>%
  plot_ly(x = ~longitude, y = ~latitude, color = ~price, text = ~haver_text, type = "scatter", mode = "marker", alpha = 0.5)
```

### Bar chart

```{r}
airbnb_data %>%
  count(neighbourhood) %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

